list=[]
list.append(input("Enter list element 1:"))
list.append(input("Enter list element 2:"))
list.append(input("Enter list element 3:"))
list.append(input("Enter list element 4:"))
list.append(input("Enter list element 5:"))
list.append(input("Enter list element 7:"))
list.append(input("Enter list element 6:"))
list.append(input("Enter list element 8:"))
print("User Entered List is:",list)
list1=set(list)
print("Set is:",list1)
list1=list.copy()
list2=list1.sort()
print("Sorted List is:",list2)
print("Second Largest Element is:",list2[-2])